FROM node:lts as dependencies
WORKDIR /var/www/Blocky
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:lts as builder
WORKDIR /var/www/Blocky
COPY . .
COPY --from=dependencies /var/www/Blocky/node_modules ./node_modules
RUN yarn build

FROM node:lts as runner
WORKDIR /var/www/Blocky
ENV NODE_ENV production

COPY --from=builder /var/www/Blocky/next.config.js ./next.config.js
COPY --from=builder /var/www/Blocky/public ./public
COPY --from=builder /var/www/Blocky/.next ./.next
COPY --from=builder /var/www/Blocky/node_modules ./node_modules
COPY --from=builder /var/www/Blocky/package.json ./package.json
EXPOSE 80
CMD ["yarn", "start"]