import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { TezosToolkit } from "@taquito/taquito";
import { BeaconWallet } from "@taquito/beacon-wallet";
import config from "../utils/config";

export default function Home() {
  const [formInput, updateFormInput] = useState("next");
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const rpc = "https://rpc.jakartanet.teztnets.xyz/";
  // const rpc = "https://jakartanet.tezos.marigold.dev/";
  const network = "jakartanet";
  const setAuth = (boolean) => {
    setIsAuthenticated(boolean);
  };

  async function connect_wallet() {
    const Tezos = new TezosToolkit(rpc);
    const options = {
      name: "Blocky",
      iconUrl:
        "https://img.lovepik.com/free-png/20220125/lovepik-real-estate-building-logo-png-image_401737177_wh860.png",
      preferredNetwork: network,
    };
    const wallet = new BeaconWallet(options);
    console.log(wallet);

    try {
      console.log("Requesting permissions...");
      const permissions = await wallet.client.requestPermissions({
        network: { type: network },
      });
      console.log("Got permissions:", permissions.address);
      permissions.address !== "undefined"
        ? setIsAuthenticated(permissions.address)
        : setIsAuthenticated(false);
    } catch (error) {
      console.log("Got error:", error);
    }
    Tezos.setWalletProvider(wallet);

    Tezos.wallet
      .at(config.NFTcontractAddress)
      .then((contract) => {
        const i = 7;

        console.log(`Incrementing storage value by ${i}...`);
        return contract.methods.increment(i).send();
      })
      .then((op) => {
        console.log(`Waiting for ${op.hash} to be confirmed...`);
        return op.confirmation(3).then(() => op.hash);
      })
      .then((hash) =>
        console.log(`Operation injected: https://ithaca.tzstats.com/${hash}`)
      )
      .catch((error) =>
        console.log(`Error: ${JSON.stringify(error, null, 2)}`)
      );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a id={formInput} href="https://nextjs.org">
            Next.js!
          </a>
        </h1>

        <input
          className={styles.input}
          placeholder="Description"
          onChange={(e) => updateFormInput(e.target.value)}
        />
        {!isAuthenticated ? (
          <button onClick={connect_wallet}>Connect Wallet</button>
        ) : (
          <p>Your address : {isAuthenticated}</p>
        )}

        {/*
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        */}
      </main>
    </div>
  );
}
